# User: admin
# Pass: admin

configs:
  secret:
    argocdServerAdminPassword: $2a$10$hu.RLTScyCnlwUbu5kGCr.SgG/yDnEKPzXIlMKO9wxoHSnwH.C//u

dex:
  enabled: false 

notifications:
  enabled: false

server:
  service:
    type: NodePort
    nodePortHttp: 31443