config:
  # -- Username to use for Git commits
  gitCommitUser: "CI Image Updater"

  # -- E-Mail address to use for Git commits
  gitCommitMail: "updater@test.com"

  # -- Changing the Git commit message
  gitCommitTemplate: "ArgoCD Image Updater updated version"

  # -- ArgoCD Image Update log level
  logLevel: "debug"
  
  registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      ping: yes
      credentials: secret:argocd/dockerhub#my-token
      limit: 20
      default: true
    