apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-qa
  namespace: argocd
spec:
  project: default
  source:
    path: stages/qa
    repoURL: https://github.com/Tautcius/argo-ecosystem.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true