apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-tests
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: tests
  triggers:
    - template:
        name: webhook-workflow-trigger-tests
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-tests
              spec:
                entrypoint: whalesay
                ttlStrategy:
                  secondsAfterCompletion: 180 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
                  secondsAfterSuccess: 180     # Time to live after workflow is successful
                  # secondsAfterFailure: 600     # Time to live after workflow fails
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by event payload from test-dep
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value